### ISSUE TITLE
Website update 

### ISSUE THREAD

**Issue by sdushantha** [sherlock-project/sherlock-project.github.io#3]
@TheYahya 
I made the website. It is very minimal because this is my first time properly using HTML and CSS. It looks fine on my computer, but I don't know if it looks good on mobile browsers. If it looks bad on mobile, I unfortunately wont be able to fix it because I am very busy at the moment :/

**Comment by sdushantha** [comment]
@TheYahya Also, you might want to put the link to this site on the `sherlock` repo

**Comment by TheYahya** [comment]
It's great, I just made some changes and cleaned it up. thank you @sdushantha
